configserver:
    name: JHipster Registry config server
    status: Connected to the JHipster Registry config server crong!

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: crong123
